var hierarchy =
[
    [ "_CPOINT", "struct__CPOINT.html", null ],
    [ "_DIACTIONA", "struct__DIACTIONA.html", null ],
    [ "_DIACTIONFORMATA", "struct__DIACTIONFORMATA.html", null ],
    [ "_DIACTIONFORMATW", "struct__DIACTIONFORMATW.html", null ],
    [ "_DIACTIONW", "struct__DIACTIONW.html", null ],
    [ "_DICOLORSET", "struct__DICOLORSET.html", null ],
    [ "_DICONFIGUREDEVICESPARAMSA", "struct__DICONFIGUREDEVICESPARAMSA.html", null ],
    [ "_DICONFIGUREDEVICESPARAMSW", "struct__DICONFIGUREDEVICESPARAMSW.html", null ],
    [ "_DIDATAFORMAT", "struct__DIDATAFORMAT.html", null ],
    [ "_DIDEVICEIMAGEINFOA", "struct__DIDEVICEIMAGEINFOA.html", null ],
    [ "_DIDEVICEIMAGEINFOHEADERA", "struct__DIDEVICEIMAGEINFOHEADERA.html", null ],
    [ "_DIDEVICEIMAGEINFOHEADERW", "struct__DIDEVICEIMAGEINFOHEADERW.html", null ],
    [ "_DIDEVICEIMAGEINFOW", "struct__DIDEVICEIMAGEINFOW.html", null ],
    [ "_DIOBJECTDATAFORMAT", "struct__DIOBJECTDATAFORMAT.html", null ],
    [ "_GLFWcontext", "struct__GLFWcontext.html", null ],
    [ "_GLFWcontextEGL", "struct__GLFWcontextEGL.html", null ],
    [ "_GLFWcontextGLX", "struct__GLFWcontextGLX.html", null ],
    [ "_GLFWcontextNSGL", "struct__GLFWcontextNSGL.html", null ],
    [ "_GLFWcontextOSMesa", "struct__GLFWcontextOSMesa.html", null ],
    [ "_GLFWcontextWGL", "struct__GLFWcontextWGL.html", null ],
    [ "_GLFWctxconfig", "struct__GLFWctxconfig.html", null ],
    [ "_GLFWcursor", "struct__GLFWcursor.html", null ],
    [ "_GLFWcursorNS", "struct__GLFWcursorNS.html", null ],
    [ "_GLFWcursorWayland", "struct__GLFWcursorWayland.html", null ],
    [ "_GLFWcursorWin32", "struct__GLFWcursorWin32.html", null ],
    [ "_GLFWcursorX11", "struct__GLFWcursorX11.html", null ],
    [ "_GLFWdecorationWayland", "struct__GLFWdecorationWayland.html", null ],
    [ "_GLFWerror", "struct__GLFWerror.html", null ],
    [ "_GLFWfbconfig", "struct__GLFWfbconfig.html", null ],
    [ "_GLFWinitconfig", "struct__GLFWinitconfig.html", null ],
    [ "_GLFWjoyelementNS", "struct__GLFWjoyelementNS.html", null ],
    [ "_GLFWjoyobjectWin32", "struct__GLFWjoyobjectWin32.html", null ],
    [ "_GLFWjoystick", "struct__GLFWjoystick.html", null ],
    [ "_GLFWjoystickLinux", "struct__GLFWjoystickLinux.html", null ],
    [ "_GLFWjoystickNS", "struct__GLFWjoystickNS.html", null ],
    [ "_GLFWjoystickWin32", "struct__GLFWjoystickWin32.html", null ],
    [ "_GLFWlibrary", "struct__GLFWlibrary.html", null ],
    [ "_GLFWlibraryEGL", "struct__GLFWlibraryEGL.html", null ],
    [ "_GLFWlibraryGLX", "struct__GLFWlibraryGLX.html", null ],
    [ "_GLFWlibraryLinux", "struct__GLFWlibraryLinux.html", null ],
    [ "_GLFWlibraryNS", "struct__GLFWlibraryNS.html", null ],
    [ "_GLFWlibraryNSGL", "struct__GLFWlibraryNSGL.html", null ],
    [ "_GLFWlibraryNull", "struct__GLFWlibraryNull.html", null ],
    [ "_GLFWlibraryOSMesa", "struct__GLFWlibraryOSMesa.html", null ],
    [ "_GLFWlibraryWayland", "struct__GLFWlibraryWayland.html", null ],
    [ "_GLFWlibraryWGL", "struct__GLFWlibraryWGL.html", null ],
    [ "_GLFWlibraryWin32", "struct__GLFWlibraryWin32.html", null ],
    [ "_GLFWlibraryX11", "struct__GLFWlibraryX11.html", null ],
    [ "_GLFWmapelement", "struct__GLFWmapelement.html", null ],
    [ "_GLFWmapping", "struct__GLFWmapping.html", null ],
    [ "_GLFWmonitor", "struct__GLFWmonitor.html", null ],
    [ "_GLFWmonitorNS", "struct__GLFWmonitorNS.html", null ],
    [ "_GLFWmonitorNull", "struct__GLFWmonitorNull.html", null ],
    [ "_GLFWmonitorWayland", "struct__GLFWmonitorWayland.html", null ],
    [ "_GLFWmonitorWin32", "struct__GLFWmonitorWin32.html", null ],
    [ "_GLFWmonitorX11", "struct__GLFWmonitorX11.html", null ],
    [ "_GLFWmutex", "struct__GLFWmutex.html", null ],
    [ "_GLFWmutexPOSIX", "struct__GLFWmutexPOSIX.html", null ],
    [ "_GLFWmutexWin32", "struct__GLFWmutexWin32.html", null ],
    [ "_GLFWobjenumWin32", "struct__GLFWobjenumWin32.html", null ],
    [ "_GLFWtimerNS", "struct__GLFWtimerNS.html", null ],
    [ "_GLFWtimerPOSIX", "struct__GLFWtimerPOSIX.html", null ],
    [ "_GLFWtimerWin32", "struct__GLFWtimerWin32.html", null ],
    [ "_GLFWtls", "struct__GLFWtls.html", null ],
    [ "_GLFWtlsPOSIX", "struct__GLFWtlsPOSIX.html", null ],
    [ "_GLFWtlsWin32", "struct__GLFWtlsWin32.html", null ],
    [ "_GLFWwindow", "struct__GLFWwindow.html", null ],
    [ "_GLFWwindowNS", "struct__GLFWwindowNS.html", null ],
    [ "_GLFWwindowNull", "struct__GLFWwindowNull.html", null ],
    [ "_GLFWwindowWayland", "struct__GLFWwindowWayland.html", null ],
    [ "_GLFWwindowWin32", "struct__GLFWwindowWin32.html", null ],
    [ "_GLFWwindowX11", "struct__GLFWwindowX11.html", null ],
    [ "_GLFWwndconfig", "struct__GLFWwndconfig.html", null ],
    [ "_XINPUT_BATTERY_INFORMATION", "struct__XINPUT__BATTERY__INFORMATION.html", null ],
    [ "_XINPUT_CAPABILITIES", "struct__XINPUT__CAPABILITIES.html", null ],
    [ "_XINPUT_GAMEPAD", "struct__XINPUT__GAMEPAD.html", null ],
    [ "_XINPUT_KEYSTROKE", "struct__XINPUT__KEYSTROKE.html", null ],
    [ "_XINPUT_STATE", "struct__XINPUT__STATE.html", null ],
    [ "_XINPUT_VIBRATION", "struct__XINPUT__VIBRATION.html", null ],
    [ "detail::actual_object_comparator< BasicJsonType >", "structdetail_1_1actual__object__comparator.html", null ],
    [ "adl_serializer< ValueType, typename >", "structadl__serializer.html", null ],
    [ "AliasInfo", "structAliasInfo.html", null ],
    [ "android_app", "structandroid__app.html", null ],
    [ "android_poll_source", "structandroid__poll__source.html", null ],
    [ "ecs::Archetype< Components >", "classecs_1_1Archetype.html", null ],
    [ "ArrayColor", "structArrayColor.html", null ],
    [ "ArrayUShort", "structArrayUShort.html", null ],
    [ "ArrayVector3", "structArrayVector3.html", null ],
    [ "AudioData", "structAudioData.html", null ],
    [ "AudioStream", "structAudioStream.html", null ],
    [ "B", null, [
      [ "detail::conjunction< B >", "structdetail_1_1conjunction_3_01B_01_4.html", null ],
      [ "detail::conjunction< B >", "structdetail_1_1conjunction_3_01B_01_4.html", null ]
    ] ],
    [ "basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >", "classbasic__json.html", null ],
    [ "detail::binary_reader< BasicJsonType, InputAdapterType, SAX >", "classdetail_1_1binary__reader.html", null ],
    [ "detail::binary_writer< BasicJsonType, CharType >", "classdetail_1_1binary__writer.html", null ],
    [ "BinaryType", null, [
      [ "byte_container_with_subtype< BinaryType >", "classbyte__container__with__subtype.html", null ],
      [ "byte_container_with_subtype< BinaryType >", "classbyte__container__with__subtype.html", null ]
    ] ],
    [ "BoneInfo", "structBoneInfo.html", null ],
    [ "bool_constant", null, [
      [ "detail::is_c_string< T >", "structdetail_1_1is__c__string.html", null ],
      [ "detail::is_c_string< T >", "structdetail_1_1is__c__string.html", null ],
      [ "detail::is_transparent< T >", "structdetail_1_1is__transparent.html", null ],
      [ "detail::is_transparent< T >", "structdetail_1_1is__transparent.html", null ]
    ] ],
    [ "detail::dtoa_impl::boundaries", "structdetail_1_1dtoa__impl_1_1boundaries.html", null ],
    [ "BoundingBox", "structBoundingBox.html", null ],
    [ "Bullet", "classBullet.html", null ],
    [ "Bunny", "structBunny.html", null ],
    [ "Button", "classButton.html", null ],
    [ "detail::dtoa_impl::cached_power", "structdetail_1_1dtoa__impl_1_1cached__power.html", null ],
    [ "Camera", "structCamera.html", null ],
    [ "Camera2D", "structCamera2D.html", null ],
    [ "Camera3D", "structCamera3D.html", null ],
    [ "cgltf_accessor", "structcgltf__accessor.html", null ],
    [ "cgltf_accessor_sparse", "structcgltf__accessor__sparse.html", null ],
    [ "cgltf_animation", "structcgltf__animation.html", null ],
    [ "cgltf_animation_channel", "structcgltf__animation__channel.html", null ],
    [ "cgltf_animation_sampler", "structcgltf__animation__sampler.html", null ],
    [ "cgltf_asset", "structcgltf__asset.html", null ],
    [ "cgltf_attribute", "structcgltf__attribute.html", null ],
    [ "cgltf_buffer", "structcgltf__buffer.html", null ],
    [ "cgltf_buffer_view", "structcgltf__buffer__view.html", null ],
    [ "cgltf_camera", "structcgltf__camera.html", null ],
    [ "cgltf_camera_orthographic", "structcgltf__camera__orthographic.html", null ],
    [ "cgltf_camera_perspective", "structcgltf__camera__perspective.html", null ],
    [ "cgltf_clearcoat", "structcgltf__clearcoat.html", null ],
    [ "cgltf_data", "structcgltf__data.html", null ],
    [ "cgltf_draco_mesh_compression", "structcgltf__draco__mesh__compression.html", null ],
    [ "cgltf_emissive_strength", "structcgltf__emissive__strength.html", null ],
    [ "cgltf_extension", "structcgltf__extension.html", null ],
    [ "cgltf_extras", "structcgltf__extras.html", null ],
    [ "cgltf_file_options", "structcgltf__file__options.html", null ],
    [ "cgltf_image", "structcgltf__image.html", null ],
    [ "cgltf_ior", "structcgltf__ior.html", null ],
    [ "cgltf_iridescence", "structcgltf__iridescence.html", null ],
    [ "cgltf_light", "structcgltf__light.html", null ],
    [ "cgltf_material", "structcgltf__material.html", null ],
    [ "cgltf_material_mapping", "structcgltf__material__mapping.html", null ],
    [ "cgltf_material_variant", "structcgltf__material__variant.html", null ],
    [ "cgltf_memory_options", "structcgltf__memory__options.html", null ],
    [ "cgltf_mesh", "structcgltf__mesh.html", null ],
    [ "cgltf_mesh_gpu_instancing", "structcgltf__mesh__gpu__instancing.html", null ],
    [ "cgltf_meshopt_compression", "structcgltf__meshopt__compression.html", null ],
    [ "cgltf_morph_target", "structcgltf__morph__target.html", null ],
    [ "cgltf_node", "structcgltf__node.html", null ],
    [ "cgltf_options", "structcgltf__options.html", null ],
    [ "cgltf_pbr_metallic_roughness", "structcgltf__pbr__metallic__roughness.html", null ],
    [ "cgltf_pbr_specular_glossiness", "structcgltf__pbr__specular__glossiness.html", null ],
    [ "cgltf_primitive", "structcgltf__primitive.html", null ],
    [ "cgltf_sampler", "structcgltf__sampler.html", null ],
    [ "cgltf_scene", "structcgltf__scene.html", null ],
    [ "cgltf_sheen", "structcgltf__sheen.html", null ],
    [ "cgltf_skin", "structcgltf__skin.html", null ],
    [ "cgltf_specular", "structcgltf__specular.html", null ],
    [ "cgltf_texture", "structcgltf__texture.html", null ],
    [ "cgltf_texture_transform", "structcgltf__texture__transform.html", null ],
    [ "cgltf_texture_view", "structcgltf__texture__view.html", null ],
    [ "cgltf_transmission", "structcgltf__transmission.html", null ],
    [ "cgltf_volume", "structcgltf__volume.html", null ],
    [ "CHANGEFILTERSTRUCT", "structCHANGEFILTERSTRUCT.html", null ],
    [ "channel", "structchannel.html", null ],
    [ "CircleWave", "structCircleWave.html", null ],
    [ "Color", "structColor.html", null ],
    [ "detail::container_input_adapter_factory_impl::container_input_adapter_factory< ContainerType, Enable >", "structdetail_1_1container__input__adapter__factory__impl_1_1container__input__adapter__factory.html", null ],
    [ "detail::container_input_adapter_factory_impl::container_input_adapter_factory< ContainerType, void_t< decltype(begin(std::declval< ContainerType >()), end(std::declval< ContainerType >()))> >", "structdetail_1_1container__input__adapter__factory__impl_1_1container__input__adapter__factory_3983614ac0e8828aa386ca24b1ddc2bd1.html", null ],
    [ "CoreData", "structCoreData.html", null ],
    [ "CubeChunk3D", "structCubeChunk3D.html", null ],
    [ "DefineInfo", "structDefineInfo.html", null ],
    [ "detail::detector< Default, AlwaysVoid, Op, Args >", "structdetail_1_1detector.html", null ],
    [ "detail::detector< Default, void_t< Op< Args... > >, Op, Args... >", "structdetail_1_1detector_3_01Default_00_01void__t_3_01Op_3_01Args_8_8_8_01_4_01_4_00_01Op_00_01Args_8_8_8_01_4.html", null ],
    [ "DICONDITION", "structDICONDITION.html", null ],
    [ "DICONSTANTFORCE", "structDICONSTANTFORCE.html", null ],
    [ "DICUSTOMFORCE", "structDICUSTOMFORCE.html", null ],
    [ "DIDEVCAPS", "structDIDEVCAPS.html", null ],
    [ "DIDEVCAPS_DX3", "structDIDEVCAPS__DX3.html", null ],
    [ "DIDEVICEINSTANCE_DX3A", "structDIDEVICEINSTANCE__DX3A.html", null ],
    [ "DIDEVICEINSTANCE_DX3W", "structDIDEVICEINSTANCE__DX3W.html", null ],
    [ "DIDEVICEINSTANCEA", "structDIDEVICEINSTANCEA.html", null ],
    [ "DIDEVICEINSTANCEW", "structDIDEVICEINSTANCEW.html", null ],
    [ "DIDEVICEOBJECTDATA", "structDIDEVICEOBJECTDATA.html", null ],
    [ "DIDEVICEOBJECTDATA_DX3", "structDIDEVICEOBJECTDATA__DX3.html", null ],
    [ "DIDEVICEOBJECTINSTANCE_DX3A", "structDIDEVICEOBJECTINSTANCE__DX3A.html", null ],
    [ "DIDEVICEOBJECTINSTANCE_DX3W", "structDIDEVICEOBJECTINSTANCE__DX3W.html", null ],
    [ "DIDEVICEOBJECTINSTANCEA", "structDIDEVICEOBJECTINSTANCEA.html", null ],
    [ "DIDEVICEOBJECTINSTANCEW", "structDIDEVICEOBJECTINSTANCEW.html", null ],
    [ "DIEFFECT", "structDIEFFECT.html", null ],
    [ "DIEFFECT_DX5", "structDIEFFECT__DX5.html", null ],
    [ "DIEFFECTINFOA", "structDIEFFECTINFOA.html", null ],
    [ "DIEFFECTINFOW", "structDIEFFECTINFOW.html", null ],
    [ "DIEFFESCAPE", "structDIEFFESCAPE.html", null ],
    [ "DIENVELOPE", "structDIENVELOPE.html", null ],
    [ "DIFILEEFFECT", "structDIFILEEFFECT.html", null ],
    [ "DIJOYSTATE", "structDIJOYSTATE.html", null ],
    [ "DIJOYSTATE2", "structDIJOYSTATE2.html", null ],
    [ "DIMOUSESTATE", "structDIMOUSESTATE.html", null ],
    [ "DIMOUSESTATE2", "structDIMOUSESTATE2.html", null ],
    [ "DIPERIODIC", "structDIPERIODIC.html", null ],
    [ "DIPROPCAL", "structDIPROPCAL.html", null ],
    [ "DIPROPCALPOV", "structDIPROPCALPOV.html", null ],
    [ "DIPROPCPOINTS", "structDIPROPCPOINTS.html", null ],
    [ "DIPROPDWORD", "structDIPROPDWORD.html", null ],
    [ "DIPROPGUIDANDPATH", "structDIPROPGUIDANDPATH.html", null ],
    [ "DIPROPHEADER", "structDIPROPHEADER.html", null ],
    [ "DIPROPPOINTER", "structDIPROPPOINTER.html", null ],
    [ "DIPROPRANGE", "structDIPROPRANGE.html", null ],
    [ "DIPROPSTRING", "structDIPROPSTRING.html", null ],
    [ "DIR", "structDIR.html", null ],
    [ "DIRAMPFORCE", "structDIRAMPFORCE.html", null ],
    [ "dirent", "structdirent.html", null ],
    [ "detail::dtoa_impl::diyfp", "structdetail_1_1dtoa__impl_1_1diyfp.html", null ],
    [ "drflac", "structdrflac.html", null ],
    [ "drflac__memory_stream", "structdrflac____memory__stream.html", null ],
    [ "drflac_allocation_callbacks", "structdrflac__allocation__callbacks.html", null ],
    [ "drflac_bs", "structdrflac__bs.html", null ],
    [ "drflac_cuesheet_track", "structdrflac__cuesheet__track.html", null ],
    [ "drflac_cuesheet_track_index", "structdrflac__cuesheet__track__index.html", null ],
    [ "drflac_cuesheet_track_iterator", "structdrflac__cuesheet__track__iterator.html", null ],
    [ "drflac_frame", "structdrflac__frame.html", null ],
    [ "drflac_frame_header", "structdrflac__frame__header.html", null ],
    [ "drflac_metadata", "structdrflac__metadata.html", null ],
    [ "drflac_seekpoint", "structdrflac__seekpoint.html", null ],
    [ "drflac_streaminfo", "structdrflac__streaminfo.html", null ],
    [ "drflac_subframe", "structdrflac__subframe.html", null ],
    [ "drflac_vorbis_comment_iterator", "structdrflac__vorbis__comment__iterator.html", null ],
    [ "drmp3", "structdrmp3.html", null ],
    [ "drmp3_allocation_callbacks", "structdrmp3__allocation__callbacks.html", null ],
    [ "drmp3_config", "structdrmp3__config.html", null ],
    [ "drmp3_seek_point", "structdrmp3__seek__point.html", null ],
    [ "drmp3dec", "structdrmp3dec.html", null ],
    [ "drmp3dec_frame_info", "structdrmp3dec__frame__info.html", null ],
    [ "drwav", "structdrwav.html", null ],
    [ "drwav__memory_stream", "structdrwav____memory__stream.html", null ],
    [ "drwav__memory_stream_write", "structdrwav____memory__stream__write.html", null ],
    [ "drwav_acid", "structdrwav__acid.html", null ],
    [ "drwav_allocation_callbacks", "structdrwav__allocation__callbacks.html", null ],
    [ "drwav_bext", "structdrwav__bext.html", null ],
    [ "drwav_chunk_header", "structdrwav__chunk__header.html", null ],
    [ "drwav_cue", "structdrwav__cue.html", null ],
    [ "drwav_cue_point", "structdrwav__cue__point.html", null ],
    [ "drwav_data_format", "structdrwav__data__format.html", null ],
    [ "drwav_fmt", "structdrwav__fmt.html", null ],
    [ "drwav_inst", "structdrwav__inst.html", null ],
    [ "drwav_list_info_text", "structdrwav__list__info__text.html", null ],
    [ "drwav_list_label_or_note", "structdrwav__list__label__or__note.html", null ],
    [ "drwav_list_labelled_cue_region", "structdrwav__list__labelled__cue__region.html", null ],
    [ "drwav_metadata", "structdrwav__metadata.html", null ],
    [ "drwav_smpl", "structdrwav__smpl.html", null ],
    [ "drwav_smpl_loop", "structdrwav__smpl__loop.html", null ],
    [ "drwav_unknown_metadata", "structdrwav__unknown__metadata.html", null ],
    [ "DWM_BLURBEHIND", "structDWM__BLURBEHIND.html", null ],
    [ "Enemy", "classEnemy.html", null ],
    [ "Engine", "classEngine.html", null ],
    [ "EnumInfo", "structEnumInfo.html", null ],
    [ "EnvItem", "structEnvItem.html", null ],
    [ "std::exception", null, [
      [ "detail::exception", "classdetail_1_1exception.html", [
        [ "detail::invalid_iterator", "classdetail_1_1invalid__iterator.html", null ],
        [ "detail::invalid_iterator", "classdetail_1_1invalid__iterator.html", null ],
        [ "detail::other_error", "classdetail_1_1other__error.html", null ],
        [ "detail::other_error", "classdetail_1_1other__error.html", null ],
        [ "detail::out_of_range", "classdetail_1_1out__of__range.html", null ],
        [ "detail::out_of_range", "classdetail_1_1out__of__range.html", null ],
        [ "detail::parse_error", "classdetail_1_1parse__error.html", null ],
        [ "detail::parse_error", "classdetail_1_1parse__error.html", null ],
        [ "detail::type_error", "classdetail_1_1type__error.html", null ],
        [ "detail::type_error", "classdetail_1_1type__error.html", null ]
      ] ],
      [ "detail::exception", "classdetail_1_1exception.html", null ]
    ] ],
    [ "detail::utility_internal::Extend< Seq, SeqSize, Rem >", "structdetail_1_1utility__internal_1_1Extend.html", null ],
    [ "detail::utility_internal::Extend< integer_sequence< T, Ints... >, SeqSize, 0 >", "structdetail_1_1utility__internal_1_1Extend_3_01integer__sequence_3_01T_00_01Ints_8_8_8_01_4_00_01SeqSize_00_010_01_4.html", null ],
    [ "detail::utility_internal::Extend< integer_sequence< T, Ints... >, SeqSize, 1 >", "structdetail_1_1utility__internal_1_1Extend_3_01integer__sequence_3_01T_00_01Ints_8_8_8_01_4_00_01SeqSize_00_011_01_4.html", null ],
    [ "detail::external_constructor< value_t >", "structdetail_1_1external__constructor.html", null ],
    [ "detail::external_constructor< value_t::array >", "structdetail_1_1external__constructor_3_01value__t_1_1array_01_4.html", null ],
    [ "detail::external_constructor< value_t::binary >", "structdetail_1_1external__constructor_3_01value__t_1_1binary_01_4.html", null ],
    [ "detail::external_constructor< value_t::boolean >", "structdetail_1_1external__constructor_3_01value__t_1_1boolean_01_4.html", null ],
    [ "detail::external_constructor< value_t::number_float >", "structdetail_1_1external__constructor_3_01value__t_1_1number__float_01_4.html", null ],
    [ "detail::external_constructor< value_t::number_integer >", "structdetail_1_1external__constructor_3_01value__t_1_1number__integer_01_4.html", null ],
    [ "detail::external_constructor< value_t::number_unsigned >", "structdetail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4.html", null ],
    [ "detail::external_constructor< value_t::object >", "structdetail_1_1external__constructor_3_01value__t_1_1object_01_4.html", null ],
    [ "detail::external_constructor< value_t::string >", "structdetail_1_1external__constructor_3_01value__t_1_1string_01_4.html", null ],
    [ "std::false_type", null, [
      [ "detail::has_from_json< BasicJsonType, T, typename >", "structdetail_1_1has__from__json.html", null ],
      [ "detail::has_from_json< BasicJsonType, T, typename >", "structdetail_1_1has__from__json.html", null ],
      [ "detail::has_non_default_from_json< BasicJsonType, T, typename >", "structdetail_1_1has__non__default__from__json.html", null ],
      [ "detail::has_non_default_from_json< BasicJsonType, T, typename >", "structdetail_1_1has__non__default__from__json.html", null ],
      [ "detail::has_to_json< BasicJsonType, T, typename >", "structdetail_1_1has__to__json.html", null ],
      [ "detail::has_to_json< BasicJsonType, T, typename >", "structdetail_1_1has__to__json.html", null ],
      [ "detail::is_basic_json< typename >", "structdetail_1_1is__basic__json.html", null ],
      [ "detail::is_basic_json< typename >", "structdetail_1_1is__basic__json.html", null ],
      [ "detail::is_comparable< Compare, A, B, typename >", "structdetail_1_1is__comparable.html", null ],
      [ "detail::is_comparable< Compare, A, B, typename >", "structdetail_1_1is__comparable.html", null ],
      [ "detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, typename >", "structdetail_1_1is__compatible__array__type__impl.html", [
        [ "detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >", "structdetail_1_1is__compatible__array__type.html", null ],
        [ "detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >", "structdetail_1_1is__compatible__array__type.html", null ]
      ] ],
      [ "detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, typename >", "structdetail_1_1is__compatible__array__type__impl.html", null ],
      [ "detail::is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, typename >", "structdetail_1_1is__compatible__integer__type__impl.html", [
        [ "detail::is_compatible_integer_type< RealIntegerType, CompatibleNumberIntegerType >", "structdetail_1_1is__compatible__integer__type.html", null ],
        [ "detail::is_compatible_integer_type< RealIntegerType, CompatibleNumberIntegerType >", "structdetail_1_1is__compatible__integer__type.html", null ]
      ] ],
      [ "detail::is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, typename >", "structdetail_1_1is__compatible__integer__type__impl.html", null ],
      [ "detail::is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, typename >", "structdetail_1_1is__compatible__object__type__impl.html", [
        [ "detail::is_compatible_object_type< BasicJsonType, CompatibleObjectType >", "structdetail_1_1is__compatible__object__type.html", null ],
        [ "detail::is_compatible_object_type< BasicJsonType, CompatibleObjectType >", "structdetail_1_1is__compatible__object__type.html", null ]
      ] ],
      [ "detail::is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, typename >", "structdetail_1_1is__compatible__object__type__impl.html", null ],
      [ "detail::is_compatible_type_impl< BasicJsonType, CompatibleType, typename >", "structdetail_1_1is__compatible__type__impl.html", [
        [ "detail::is_compatible_type< BasicJsonType, CompatibleType >", "structdetail_1_1is__compatible__type.html", null ],
        [ "detail::is_compatible_type< BasicJsonType, CompatibleType >", "structdetail_1_1is__compatible__type.html", null ]
      ] ],
      [ "detail::is_compatible_type_impl< BasicJsonType, CompatibleType, typename >", "structdetail_1_1is__compatible__type__impl.html", null ],
      [ "detail::is_complete_type< T, typename >", "structdetail_1_1is__complete__type.html", null ],
      [ "detail::is_complete_type< T, typename >", "structdetail_1_1is__complete__type.html", null ],
      [ "detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, typename >", "structdetail_1_1is__constructible__array__type__impl.html", [
        [ "detail::is_constructible_array_type< BasicJsonType, ConstructibleArrayType >", "structdetail_1_1is__constructible__array__type.html", null ],
        [ "detail::is_constructible_array_type< BasicJsonType, ConstructibleArrayType >", "structdetail_1_1is__constructible__array__type.html", null ]
      ] ],
      [ "detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, typename >", "structdetail_1_1is__constructible__array__type__impl.html", null ],
      [ "detail::is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, typename >", "structdetail_1_1is__constructible__object__type__impl.html", [
        [ "detail::is_constructible_object_type< BasicJsonType, ConstructibleObjectType >", "structdetail_1_1is__constructible__object__type.html", null ],
        [ "detail::is_constructible_object_type< BasicJsonType, ConstructibleObjectType >", "structdetail_1_1is__constructible__object__type.html", null ]
      ] ],
      [ "detail::is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, typename >", "structdetail_1_1is__constructible__object__type__impl.html", null ],
      [ "detail::is_constructible_tuple< T1, T2 >", "structdetail_1_1is__constructible__tuple.html", null ],
      [ "detail::is_constructible_tuple< T1, T2 >", "structdetail_1_1is__constructible__tuple.html", null ],
      [ "detail::is_iterator_traits< T, typename >", "structdetail_1_1is__iterator__traits.html", null ],
      [ "detail::is_iterator_traits< T, typename >", "structdetail_1_1is__iterator__traits.html", null ],
      [ "detail::is_json_iterator_of< BasicJsonType, T >", "structdetail_1_1is__json__iterator__of.html", null ],
      [ "detail::is_json_iterator_of< BasicJsonType, T >", "structdetail_1_1is__json__iterator__of.html", null ],
      [ "detail::is_json_ref< typename >", "structdetail_1_1is__json__ref.html", null ],
      [ "detail::is_json_ref< typename >", "structdetail_1_1is__json__ref.html", null ],
      [ "detail::is_specialization_of< Primary, T >", "structdetail_1_1is__specialization__of.html", null ],
      [ "detail::is_specialization_of< Primary, T >", "structdetail_1_1is__specialization__of.html", null ]
    ] ],
    [ "detail::file_input_adapter", "classdetail_1_1file__input__adapter.html", null ],
    [ "FilePathList", "structFilePathList.html", null ],
    [ "float16", "structfloat16.html", null ],
    [ "float3", "structfloat3.html", null ],
    [ "Font", "structFont.html", null ],
    [ "detail::from_json_fn", "structdetail_1_1from__json__fn.html", null ],
    [ "FunctionInfo", "structFunctionInfo.html", null ],
    [ "GameObject", "classGameObject.html", null ],
    [ "detail::utility_internal::Gen< T, N >", "structdetail_1_1utility__internal_1_1Gen.html", null ],
    [ "detail::utility_internal::Gen< T, 0 >", "structdetail_1_1utility__internal_1_1Gen_3_01T_00_010_01_4.html", null ],
    [ "GestureEvent", "structGestureEvent.html", null ],
    [ "gladGLversionStruct", "structgladGLversionStruct.html", null ],
    [ "GLFWgamepadstate", "structGLFWgamepadstate.html", null ],
    [ "GLFWgammaramp", "structGLFWgammaramp.html", null ],
    [ "GLFWimage", "structGLFWimage.html", null ],
    [ "GLFWvidmode", "structGLFWvidmode.html", null ],
    [ "GlyphInfo", "structGlyphInfo.html", null ],
    [ "GolUpdateCmd", "structGolUpdateCmd.html", null ],
    [ "GolUpdateSSBO", "structGolUpdateSSBO.html", null ],
    [ "GuiStyleProp", "structGuiStyleProp.html", null ],
    [ "detail::has_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structdetail_1_1has__from__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_9is__basic__json_3_01T_01_4_1_1value_01_4_01_4.html", null ],
    [ "detail::has_non_default_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structdetail_1_1has__non__default__from__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_912047717fa07cfa9d99fe9eafcf1e11e.html", null ],
    [ "detail::has_to_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structdetail_1_1has__to__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_9is__basic__json_3_01T_01_4_1_1value_01_4_01_4.html", null ],
    [ "std::hash< nlohmann::NLOHMANN_BASIC_JSON_TPL >", "structstd_1_1hash_3_01nlohmann_1_1NLOHMANN__BASIC__JSON__TPL_01_4.html", null ],
    [ "std::hash< udp::endpoint >", "structstd_1_1hash_3_01udp_1_1endpoint_01_4.html", null ],
    [ "detail::identity_tag< T >", "structdetail_1_1identity__tag.html", null ],
    [ "idGenerator", "classidGenerator.html", null ],
    [ "Image", "structImage.html", null ],
    [ "detail::input_stream_adapter", "classdetail_1_1input__stream__adapter.html", null ],
    [ "detail::integer_sequence< T, Ints >", "structdetail_1_1integer__sequence.html", null ],
    [ "std::integral_constant", null, [
      [ "detail::has_key_compare< T >", "structdetail_1_1has__key__compare.html", null ],
      [ "detail::has_key_compare< T >", "structdetail_1_1has__key__compare.html", null ],
      [ "detail::is_basic_json_context< BasicJsonContext >", "structdetail_1_1is__basic__json__context.html", null ],
      [ "detail::is_basic_json_context< BasicJsonContext >", "structdetail_1_1is__basic__json__context.html", null ],
      [ "detail::negation< B >", "structdetail_1_1negation.html", null ],
      [ "detail::negation< B >", "structdetail_1_1negation.html", null ],
      [ "std::tuple_size<::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__size_3_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01IteratorType_01_4_01_4.html", null ],
      [ "std::tuple_size<::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__size_3_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01IteratorType_01_4_01_4.html", null ]
    ] ],
    [ "detail::internal_iterator< BasicJsonType >", "structdetail_1_1internal__iterator.html", null ],
    [ "detail::internal_iterator< typename std::remove_const< BasicJsonType >::type >", "structdetail_1_1internal__iterator.html", null ],
    [ "detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, enable_if_t< is_detected< iterator_t, CompatibleArrayType >::value &&is_iterator_traits< iterator_traits< detected_t< iterator_t, CompatibleArrayType > > >::value &&!std::is_same< CompatibleArrayType, detected_t< range_value_t, CompatibleArrayType > >::value > >", "structdetail_1_1is__compatible__array__type__impl_3_01BasicJsonType_00_01CompatibleArrayType_00_ba7b30737b5c65ad9adb609a3762b85a.html", null ],
    [ "detail::is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, enable_if_t< std::is_integral< RealIntegerType >::value &&std::is_integral< CompatibleNumberIntegerType >::value &&!std::is_same< bool, CompatibleNumberIntegerType >::value > >", "structdetail_1_1is__compatible__integer__type__impl_3_01RealIntegerType_00_01CompatibleNumberInt5b484fcfc2d1ae63b1211da72eabe33b.html", null ],
    [ "detail::is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, enable_if_t< is_detected< mapped_type_t, CompatibleObjectType >::value &&is_detected< key_type_t, CompatibleObjectType >::value > >", "structdetail_1_1is__compatible__object__type__impl_3_01BasicJsonType_00_01CompatibleObjectType_01530c59509aa77cdb5f1e95cf109944f.html", null ],
    [ "detail::is_compatible_string_type< BasicJsonType, CompatibleStringType >", "structdetail_1_1is__compatible__string__type.html", null ],
    [ "detail::is_compatible_type_impl< BasicJsonType, CompatibleType, enable_if_t< is_complete_type< CompatibleType >::value > >", "structdetail_1_1is__compatible__type__impl_3_01BasicJsonType_00_01CompatibleType_00_01enable__if67e19080e9bd0cd565bd49f604895399.html", null ],
    [ "std::is_constructible", null, [
      [ "detail::is_constructible< T, Args >", "structdetail_1_1is__constructible.html", null ],
      [ "detail::is_constructible< T, Args >", "structdetail_1_1is__constructible.html", null ]
    ] ],
    [ "detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< !std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value &&!is_compatible_string_type< BasicJsonType, ConstructibleArrayType >::value &&is_default_constructible< ConstructibleArrayType >::value &&(std::is_move_assignable< ConstructibleArrayType >::value||std::is_copy_assignable< ConstructibleArrayType >::value)&&is_detected< iterator_t, ConstructibleArrayType >::value &&is_iterator_traits< iterator_traits< detected_t< iterator_t, ConstructibleArrayType > > >::value &&is_detected< range_value_t, ConstructibleArrayType >::value &&!std::is_same< ConstructibleArrayType, detected_t< range_value_t, ConstructibleArrayType > >::value &&is_complete_type< detected_t< range_value_t, ConstructibleArrayType > >::value > >", "structdetail_1_1is__constructible__array__type__impl_3_01BasicJsonType_00_01ConstructibleArrayTy3a773789b90b07cf1d15e358c6d585ac.html", null ],
    [ "detail::is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, enable_if_t< is_detected< mapped_type_t, ConstructibleObjectType >::value &&is_detected< key_type_t, ConstructibleObjectType >::value > >", "structdetail_1_1is__constructible__object__type__impl_3_01BasicJsonType_00_01ConstructibleObject435b838380c31b9738383402f7bb5943.html", null ],
    [ "detail::is_constructible_string_type< BasicJsonType, ConstructibleStringType >", "structdetail_1_1is__constructible__string__type.html", null ],
    [ "std::is_default_constructible", null, [
      [ "detail::is_default_constructible< T >", "structdetail_1_1is__default__constructible.html", null ],
      [ "detail::is_default_constructible< T >", "structdetail_1_1is__default__constructible.html", null ]
    ] ],
    [ "is_detected", null, [
      [ "detail::is_detected_lazy< Op, Args >", "structdetail_1_1is__detected__lazy.html", null ],
      [ "detail::is_detected_lazy< Op, Args >", "structdetail_1_1is__detected__lazy.html", null ]
    ] ],
    [ "detail::is_getable< BasicJsonType, T >", "structdetail_1_1is__getable.html", null ],
    [ "detail::is_iterator_of_multibyte< T >", "structdetail_1_1is__iterator__of__multibyte.html", null ],
    [ "detail::is_iterator_traits< iterator_traits< T > >", "structdetail_1_1is__iterator__traits_3_01iterator__traits_3_01T_01_4_01_4.html", null ],
    [ "detail::is_ordered_map< T >", "structdetail_1_1is__ordered__map.html", null ],
    [ "detail::is_range< T >", "structdetail_1_1is__range.html", null ],
    [ "detail::is_sax< SAX, BasicJsonType >", "structdetail_1_1is__sax.html", null ],
    [ "detail::is_sax_static_asserts< SAX, BasicJsonType >", "structdetail_1_1is__sax__static__asserts.html", null ],
    [ "detail::iter_impl< BasicJsonType >", "classdetail_1_1iter__impl.html", null ],
    [ "detail::iteration_proxy< IteratorType >", "classdetail_1_1iteration__proxy.html", null ],
    [ "detail::iteration_proxy_value< IteratorType >", "classdetail_1_1iteration__proxy__value.html", null ],
    [ "detail::iterator_input_adapter< IteratorType >", "classdetail_1_1iterator__input__adapter.html", null ],
    [ "detail::iterator_input_adapter_factory< IteratorType, Enable >", "structdetail_1_1iterator__input__adapter__factory.html", null ],
    [ "detail::iterator_input_adapter_factory< IteratorType, enable_if_t< is_iterator_of_multibyte< IteratorType >::value > >", "structdetail_1_1iterator__input__adapter__factory_3_01IteratorType_00_01enable__if__t_3_01is__it379df2cab17a32e3e44924a3e0b8f300.html", null ],
    [ "detail::iterator_traits< T, typename >", "structdetail_1_1iterator__traits.html", null ],
    [ "detail::iterator_traits< T *, enable_if_t< std::is_object< T >::value > >", "structdetail_1_1iterator__traits_3_01T_01_5_00_01enable__if__t_3_01std_1_1is__object_3_01T_01_4_1_1value_01_4_01_4.html", null ],
    [ "detail::iterator_types< It, typename >", "structdetail_1_1iterator__types.html", null ],
    [ "detail::iterator_types< It, void_t< typename It::difference_type, typename It::value_type, typename It::pointer, typename It::reference, typename It::iterator_category > >", "structdetail_1_1iterator__types_3_01It_00_01void__t_3_01typename_01It_1_1difference__type_00_01tce77e1bdc2e5b392df295e4bdf270278.html", null ],
    [ "detail::iterator_types< T >", "structdetail_1_1iterator__types.html", [
      [ "detail::iterator_traits< T, enable_if_t< !std::is_pointer< T >::value > >", "structdetail_1_1iterator__traits_3_01T_00_01enable__if__t_3_01_9std_1_1is__pointer_3_01T_01_4_1_1value_01_4_01_4.html", null ],
      [ "detail::iterator_traits< T, enable_if_t< !std::is_pointer< T >::value > >", "structdetail_1_1iterator__traits_3_01T_00_01enable__if__t_3_01_9std_1_1is__pointer_3_01T_01_4_1_1value_01_4_01_4.html", null ]
    ] ],
    [ "jar_mod_context_t", "structjar__mod__context__t.html", null ],
    [ "jar_mod_tracker_buffer_state_", "structjar__mod__tracker__buffer__state__.html", null ],
    [ "json_pointer< RefStringType >", "classjson__pointer.html", null ],
    [ "detail::json_ref< BasicJsonType >", "classdetail_1_1json__ref.html", null ],
    [ "json_sax< BasicJsonType >", "structjson__sax.html", null ],
    [ "detail::json_sax_acceptor< BasicJsonType >", "classdetail_1_1json__sax__acceptor.html", null ],
    [ "detail::json_sax_dom_callback_parser< BasicJsonType >", "classdetail_1_1json__sax__dom__callback__parser.html", null ],
    [ "detail::json_sax_dom_parser< BasicJsonType >", "classdetail_1_1json__sax__dom__parser.html", null ],
    [ "std::less< ::nlohmann::detail::value_t >", "structstd_1_1less_3_01_1_1nlohmann_1_1detail_1_1value__t_01_4.html", null ],
    [ "detail::lexer_base< BasicJsonType >", "classdetail_1_1lexer__base.html", [
      [ "detail::lexer< BasicJsonType, InputAdapterType >", "classdetail_1_1lexer.html", null ],
      [ "detail::lexer< BasicJsonType, InputAdapterType >", "classdetail_1_1lexer.html", null ]
    ] ],
    [ "Light", "classLight.html", null ],
    [ "LightInfo", "structLightInfo.html", null ],
    [ "ma_allocation_callbacks", "structma__allocation__callbacks.html", null ],
    [ "ma_async_notification_callbacks", "structma__async__notification__callbacks.html", null ],
    [ "ma_async_notification_event", "structma__async__notification__event.html", null ],
    [ "ma_async_notification_poll", "structma__async__notification__poll.html", null ],
    [ "ma_audio_buffer", "structma__audio__buffer.html", null ],
    [ "ma_audio_buffer_config", "structma__audio__buffer__config.html", null ],
    [ "ma_audio_buffer_ref", "structma__audio__buffer__ref.html", null ],
    [ "ma_backend_callbacks", "structma__backend__callbacks.html", null ],
    [ "ma_biquad", "structma__biquad.html", null ],
    [ "ma_biquad_coefficient", "unionma__biquad__coefficient.html", null ],
    [ "ma_biquad_config", "structma__biquad__config.html", null ],
    [ "ma_biquad_node", "structma__biquad__node.html", null ],
    [ "ma_biquad_node_config", "structma__biquad__node__config.html", null ],
    [ "ma_bpf", "structma__bpf.html", null ],
    [ "ma_bpf2", "structma__bpf2.html", null ],
    [ "ma_bpf2_config", "structma__bpf2__config.html", null ],
    [ "ma_bpf_config", "structma__bpf__config.html", null ],
    [ "ma_bpf_node", "structma__bpf__node.html", null ],
    [ "ma_bpf_node_config", "structma__bpf__node__config.html", null ],
    [ "ma_channel_converter", "structma__channel__converter.html", null ],
    [ "ma_channel_converter_config", "structma__channel__converter__config.html", null ],
    [ "ma_context", "structma__context.html", null ],
    [ "ma_context_command__wasapi", "structma__context__command____wasapi.html", null ],
    [ "ma_context_config", "structma__context__config.html", null ],
    [ "ma_data_converter", "structma__data__converter.html", null ],
    [ "ma_data_converter_config", "structma__data__converter__config.html", null ],
    [ "ma_data_source_base", "structma__data__source__base.html", null ],
    [ "ma_data_source_config", "structma__data__source__config.html", null ],
    [ "ma_data_source_node", "structma__data__source__node.html", null ],
    [ "ma_data_source_node_config", "structma__data__source__node__config.html", null ],
    [ "ma_data_source_vtable", "structma__data__source__vtable.html", null ],
    [ "ma_decoder", "structma__decoder.html", null ],
    [ "ma_decoder_config", "structma__decoder__config.html", null ],
    [ "ma_decoding_backend_config", "structma__decoding__backend__config.html", null ],
    [ "ma_decoding_backend_vtable", "structma__decoding__backend__vtable.html", null ],
    [ "ma_default_vfs", "structma__default__vfs.html", null ],
    [ "ma_delay", "structma__delay.html", null ],
    [ "ma_delay_config", "structma__delay__config.html", null ],
    [ "ma_delay_node", "structma__delay__node.html", null ],
    [ "ma_delay_node_config", "structma__delay__node__config.html", null ],
    [ "ma_device", "structma__device.html", null ],
    [ "ma_device_config", "structma__device__config.html", null ],
    [ "ma_device_descriptor", "structma__device__descriptor.html", null ],
    [ "ma_device_id", "unionma__device__id.html", null ],
    [ "ma_device_info", "structma__device__info.html", null ],
    [ "ma_device_job_thread", "structma__device__job__thread.html", null ],
    [ "ma_device_job_thread_config", "structma__device__job__thread__config.html", null ],
    [ "ma_device_notification", "structma__device__notification.html", null ],
    [ "ma_duplex_rb", "structma__duplex__rb.html", null ],
    [ "ma_encoder", "structma__encoder.html", null ],
    [ "ma_encoder_config", "structma__encoder__config.html", null ],
    [ "ma_engine", "structma__engine.html", null ],
    [ "ma_engine_config", "structma__engine__config.html", null ],
    [ "ma_engine_node", "structma__engine__node.html", null ],
    [ "ma_engine_node_config", "structma__engine__node__config.html", null ],
    [ "ma_event", "structma__event.html", null ],
    [ "ma_fader", "structma__fader.html", null ],
    [ "ma_fader_config", "structma__fader__config.html", null ],
    [ "ma_fence", "structma__fence.html", null ],
    [ "ma_file_info", "structma__file__info.html", null ],
    [ "ma_gainer", "structma__gainer.html", null ],
    [ "ma_gainer_config", "structma__gainer__config.html", null ],
    [ "ma_hishelf2", "structma__hishelf2.html", null ],
    [ "ma_hishelf2_config", "structma__hishelf2__config.html", null ],
    [ "ma_hishelf_node", "structma__hishelf__node.html", null ],
    [ "ma_hishelf_node_config", "structma__hishelf__node__config.html", null ],
    [ "ma_hpf", "structma__hpf.html", null ],
    [ "ma_hpf1", "structma__hpf1.html", null ],
    [ "ma_hpf1_config", "structma__hpf1__config.html", null ],
    [ "ma_hpf2", "structma__hpf2.html", null ],
    [ "ma_hpf_config", "structma__hpf__config.html", null ],
    [ "ma_hpf_node", "structma__hpf__node.html", null ],
    [ "ma_hpf_node_config", "structma__hpf__node__config.html", null ],
    [ "ma_job", "structma__job.html", null ],
    [ "ma_job_queue", "structma__job__queue.html", null ],
    [ "ma_job_queue_config", "structma__job__queue__config.html", null ],
    [ "ma_lcg", "structma__lcg.html", null ],
    [ "ma_linear_resampler", "structma__linear__resampler.html", null ],
    [ "ma_linear_resampler_config", "structma__linear__resampler__config.html", null ],
    [ "ma_log", "structma__log.html", null ],
    [ "ma_log_callback", "structma__log__callback.html", null ],
    [ "ma_loshelf2", "structma__loshelf2.html", null ],
    [ "ma_loshelf2_config", "structma__loshelf2__config.html", null ],
    [ "ma_loshelf_node", "structma__loshelf__node.html", null ],
    [ "ma_loshelf_node_config", "structma__loshelf__node__config.html", null ],
    [ "ma_lpf", "structma__lpf.html", null ],
    [ "ma_lpf1", "structma__lpf1.html", null ],
    [ "ma_lpf1_config", "structma__lpf1__config.html", null ],
    [ "ma_lpf2", "structma__lpf2.html", null ],
    [ "ma_lpf_config", "structma__lpf__config.html", null ],
    [ "ma_lpf_node", "structma__lpf__node.html", null ],
    [ "ma_lpf_node_config", "structma__lpf__node__config.html", null ],
    [ "ma_node_base", "structma__node__base.html", null ],
    [ "ma_node_config", "structma__node__config.html", null ],
    [ "ma_node_graph", "structma__node__graph.html", null ],
    [ "ma_node_graph_config", "structma__node__graph__config.html", null ],
    [ "ma_node_input_bus", "structma__node__input__bus.html", null ],
    [ "ma_node_output_bus", "structma__node__output__bus.html", null ],
    [ "ma_node_vtable", "structma__node__vtable.html", null ],
    [ "ma_noise", "structma__noise.html", null ],
    [ "ma_noise_config", "structma__noise__config.html", null ],
    [ "ma_notch2", "structma__notch2.html", null ],
    [ "ma_notch2_config", "structma__notch2__config.html", null ],
    [ "ma_notch_node", "structma__notch__node.html", null ],
    [ "ma_notch_node_config", "structma__notch__node__config.html", null ],
    [ "ma_paged_audio_buffer", "structma__paged__audio__buffer.html", null ],
    [ "ma_paged_audio_buffer_config", "structma__paged__audio__buffer__config.html", null ],
    [ "ma_paged_audio_buffer_data", "structma__paged__audio__buffer__data.html", null ],
    [ "ma_paged_audio_buffer_page", "structma__paged__audio__buffer__page.html", null ],
    [ "ma_panner", "structma__panner.html", null ],
    [ "ma_panner_config", "structma__panner__config.html", null ],
    [ "ma_pcm_rb", "structma__pcm__rb.html", null ],
    [ "ma_peak2", "structma__peak2.html", null ],
    [ "ma_peak2_config", "structma__peak2__config.html", null ],
    [ "ma_peak_node", "structma__peak__node.html", null ],
    [ "ma_peak_node_config", "structma__peak__node__config.html", null ],
    [ "ma_rb", "structma__rb.html", null ],
    [ "ma_resampler", "structma__resampler.html", null ],
    [ "ma_resampler_config", "structma__resampler__config.html", null ],
    [ "ma_resampling_backend_vtable", "structma__resampling__backend__vtable.html", null ],
    [ "ma_resource_manager", "structma__resource__manager.html", null ],
    [ "ma_resource_manager_config", "structma__resource__manager__config.html", null ],
    [ "ma_resource_manager_data_buffer", "structma__resource__manager__data__buffer.html", null ],
    [ "ma_resource_manager_data_buffer_node", "structma__resource__manager__data__buffer__node.html", null ],
    [ "ma_resource_manager_data_source", "structma__resource__manager__data__source.html", null ],
    [ "ma_resource_manager_data_source_config", "structma__resource__manager__data__source__config.html", null ],
    [ "ma_resource_manager_data_stream", "structma__resource__manager__data__stream.html", null ],
    [ "ma_resource_manager_data_supply", "structma__resource__manager__data__supply.html", null ],
    [ "ma_resource_manager_pipeline_notifications", "structma__resource__manager__pipeline__notifications.html", null ],
    [ "ma_resource_manager_pipeline_stage_notification", "structma__resource__manager__pipeline__stage__notification.html", null ],
    [ "ma_semaphore", "structma__semaphore.html", null ],
    [ "ma_slot_allocator", "structma__slot__allocator.html", null ],
    [ "ma_slot_allocator_config", "structma__slot__allocator__config.html", null ],
    [ "ma_slot_allocator_group", "structma__slot__allocator__group.html", null ],
    [ "ma_sound", "structma__sound.html", null ],
    [ "ma_sound_config", "structma__sound__config.html", null ],
    [ "ma_sound_inlined", "structma__sound__inlined.html", null ],
    [ "ma_spatializer", "structma__spatializer.html", null ],
    [ "ma_spatializer_config", "structma__spatializer__config.html", null ],
    [ "ma_spatializer_listener", "structma__spatializer__listener.html", null ],
    [ "ma_spatializer_listener_config", "structma__spatializer__listener__config.html", null ],
    [ "ma_splitter_node", "structma__splitter__node.html", null ],
    [ "ma_splitter_node_config", "structma__splitter__node__config.html", null ],
    [ "ma_timer", "unionma__timer.html", null ],
    [ "ma_vec3f", "structma__vec3f.html", null ],
    [ "ma_vfs_callbacks", "structma__vfs__callbacks.html", null ],
    [ "ma_waveform", "structma__waveform.html", null ],
    [ "ma_waveform_config", "structma__waveform__config.html", null ],
    [ "detail::make_void< Ts >", "structdetail_1_1make__void.html", null ],
    [ "Map", "structMap.html", null ],
    [ "Material", "structMaterial.html", null ],
    [ "MaterialMap", "structMaterialMap.html", null ],
    [ "Matrix", "structMatrix.html", null ],
    [ "Mesh", "structMesh.html", null ],
    [ "Model", "structModel.html", null ],
    [ "ModelAnimation", "structModelAnimation.html", null ],
    [ "module", "structmodule.html", null ],
    [ "MsfCookedFrame", "structMsfCookedFrame.html", null ],
    [ "MsfGifBuffer", "structMsfGifBuffer.html", null ],
    [ "MsfGifResult", "structMsfGifResult.html", null ],
    [ "MsfGifState", "structMsfGifState.html", null ],
    [ "Music", "structMusic.html", null ],
    [ "MyMusic", "structMyMusic.html", null ],
    [ "MySound", "structMySound.html", null ],
    [ "MyTexture", "structMyTexture.html", null ],
    [ "detail::nonesuch", "structdetail_1_1nonesuch.html", null ],
    [ "note", "structnote.html", null ],
    [ "NPatchInfo", "structNPatchInfo.html", null ],
    [ "<NSApplicationDelegate>", null, [
      [ "GLFWApplicationDelegate", "interfaceGLFWApplicationDelegate.html", null ]
    ] ],
    [ "NSObject", null, [
      [ "GLFWApplicationDelegate", "interfaceGLFWApplicationDelegate.html", null ],
      [ "GLFWHelper", "interfaceGLFWHelper.html", null ],
      [ "GLFWWindowDelegate", "interfaceGLFWWindowDelegate.html", null ]
    ] ],
    [ "<NSTextInputClient>", null, [
      [ "GLFWContentView", "interfaceGLFWContentView.html", null ]
    ] ],
    [ "NSView", null, [
      [ "GLFWContentView", "interfaceGLFWContentView.html", null ]
    ] ],
    [ "NSWindow", null, [
      [ "GLFWWindow", "interfaceGLFWWindow.html", null ]
    ] ],
    [ "option", "structoption.html", null ],
    [ "detail::output_adapter< CharType, StringType >", "classdetail_1_1output__adapter.html", null ],
    [ "detail::output_adapter_protocol< CharType >", "structdetail_1_1output__adapter__protocol.html", [
      [ "detail::output_stream_adapter< CharType >", "classdetail_1_1output__stream__adapter.html", null ],
      [ "detail::output_stream_adapter< CharType >", "classdetail_1_1output__stream__adapter.html", null ],
      [ "detail::output_string_adapter< CharType, StringType >", "classdetail_1_1output__string__adapter.html", null ],
      [ "detail::output_string_adapter< CharType, StringType >", "classdetail_1_1output__string__adapter.html", null ],
      [ "detail::output_vector_adapter< CharType, AllocatorType >", "classdetail_1_1output__vector__adapter.html", null ],
      [ "detail::output_vector_adapter< CharType, AllocatorType >", "classdetail_1_1output__vector__adapter.html", null ]
    ] ],
    [ "par_shapes_mesh_s", "structpar__shapes__mesh__s.html", null ],
    [ "detail::parser< BasicJsonType, InputAdapterType >", "classdetail_1_1parser.html", null ],
    [ "Particle", "structParticle.html", null ],
    [ "Particle2D", "classParticle2D.html", null ],
    [ "Player", "classPlayer.html", null ],
    [ "Point", "structPoint.html", null ],
    [ "ecs::Position", "structecs_1_1Position.html", null ],
    [ "detail::position_t", "structdetail_1_1position__t.html", null ],
    [ "detail::primitive_iterator_t", "classdetail_1_1primitive__iterator__t.html", null ],
    [ "detail::priority_tag< N >", "structdetail_1_1priority__tag.html", null ],
    [ "detail::priority_tag< 0 >", "structdetail_1_1priority__tag_3_010_01_4.html", null ],
    [ "qoi_desc", "structqoi__desc.html", null ],
    [ "rAudioBuffer", "structrAudioBuffer.html", null ],
    [ "rAudioProcessor", "structrAudioProcessor.html", null ],
    [ "Ray", "structRay.html", null ],
    [ "RayCollision", "structRayCollision.html", null ],
    [ "Rectangle", "structRectangle.html", null ],
    [ "RenderTexture", "structRenderTexture.html", null ],
    [ "std::reverse_iterator", null, [
      [ "detail::json_reverse_iterator< Base >", "classdetail_1_1json__reverse__iterator.html", null ],
      [ "detail::json_reverse_iterator< Base >", "classdetail_1_1json__reverse__iterator.html", null ]
    ] ],
    [ "rlDrawCall", "structrlDrawCall.html", null ],
    [ "rlRenderBatch", "structrlRenderBatch.html", null ],
    [ "rlVertexBuffer", "structrlVertexBuffer.html", null ],
    [ "sample", "structsample.html", null ],
    [ "sdefl", "structsdefl.html", null ],
    [ "sdefl_code_words", "structsdefl__code__words.html", null ],
    [ "sdefl_codes", "structsdefl__codes.html", null ],
    [ "sdefl_freq", "structsdefl__freq.html", null ],
    [ "sdefl_lens", "structsdefl__lens.html", null ],
    [ "sdefl_seqt", "structsdefl__seqt.html", null ],
    [ "detail::serializer< BasicJsonType >", "classdetail_1_1serializer.html", null ],
    [ "Shader", "structShader.html", null ],
    [ "ShadowGeometry", "structShadowGeometry.html", null ],
    [ "sinfl", "structsinfl.html", null ],
    [ "Size", "structSize.html", null ],
    [ "Slider", "classSlider.html", null ],
    [ "Sound", "structSound.html", null ],
    [ "detail::span_input_adapter", "classdetail_1_1span__input__adapter.html", null ],
    [ "ecs::SparseMap< Component >", "classecs_1_1SparseMap.html", null ],
    [ "Spot", "structSpot.html", null ],
    [ "Star", "structStar.html", null ],
    [ "detail::static_const< T >", "structdetail_1_1static__const.html", null ],
    [ "stb_vorbis_alloc", "structstb__vorbis__alloc.html", null ],
    [ "stb_vorbis_info", "structstb__vorbis__info.html", null ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", null ],
    [ "stbrp_context", "structstbrp__context.html", null ],
    [ "stbrp_node", "structstbrp__node.html", null ],
    [ "stbrp_rect", "structstbrp__rect.html", null ],
    [ "stbtt__bitmap", "structstbtt____bitmap.html", null ],
    [ "stbtt__buf", "structstbtt____buf.html", null ],
    [ "stbtt_aligned_quad", "structstbtt__aligned__quad.html", null ],
    [ "stbtt_bakedchar", "structstbtt__bakedchar.html", null ],
    [ "stbtt_fontinfo", "structstbtt__fontinfo.html", null ],
    [ "stbtt_kerningentry", "structstbtt__kerningentry.html", null ],
    [ "stbtt_pack_context", "structstbtt__pack__context.html", null ],
    [ "stbtt_pack_range", "structstbtt__pack__range.html", null ],
    [ "stbtt_packedchar", "structstbtt__packedchar.html", null ],
    [ "stbtt_vertex", "structstbtt__vertex.html", null ],
    [ "StructInfo", "structStructInfo.html", null ],
    [ "Texture", "structTexture.html", null ],
    [ "tinyobj_attrib_t", "structtinyobj__attrib__t.html", null ],
    [ "tinyobj_material_t", "structtinyobj__material__t.html", null ],
    [ "tinyobj_shape_t", "structtinyobj__shape__t.html", null ],
    [ "tinyobj_vertex_index_t", "structtinyobj__vertex__index__t.html", null ],
    [ "detail::to_json_fn", "structdetail_1_1to__json__fn.html", null ],
    [ "track_state_", "structtrack__state__.html", null ],
    [ "tracker_state_", "structtracker__state__.html", null ],
    [ "tracker_state_instrument_", "structtracker__state__instrument__.html", null ],
    [ "Transform", "structTransform.html", null ],
    [ "std::true_type", null, [
      [ "detail::conjunction< is_constructible< T1, Args >... >", "structdetail_1_1conjunction.html", [
        [ "detail::is_constructible_tuple< T1, std::tuple< Args... > >", "structdetail_1_1is__constructible__tuple_3_01T1_00_01std_1_1tuple_3_01Args_8_8_8_01_4_01_4.html", null ],
        [ "detail::is_constructible_tuple< T1, std::tuple< Args... > >", "structdetail_1_1is__constructible__tuple_3_01T1_00_01std_1_1tuple_3_01Args_8_8_8_01_4_01_4.html", null ]
      ] ],
      [ "detail::conjunction< is_default_constructible< T1 >, is_default_constructible< T2 > >", "structdetail_1_1conjunction.html", [
        [ "detail::is_default_constructible< const std::pair< T1, T2 > >", "structdetail_1_1is__default__constructible_3_01const_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", [
          [ "detail::is_constructible< const std::pair< T1, T2 > >", "structdetail_1_1is__constructible_3_01const_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ],
          [ "detail::is_constructible< const std::pair< T1, T2 > >", "structdetail_1_1is__constructible_3_01const_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ]
        ] ],
        [ "detail::is_default_constructible< const std::pair< T1, T2 > >", "structdetail_1_1is__default__constructible_3_01const_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ],
        [ "detail::is_default_constructible< std::pair< T1, T2 > >", "structdetail_1_1is__default__constructible_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", [
          [ "detail::is_constructible< std::pair< T1, T2 > >", "structdetail_1_1is__constructible_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ],
          [ "detail::is_constructible< std::pair< T1, T2 > >", "structdetail_1_1is__constructible_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ]
        ] ],
        [ "detail::is_default_constructible< std::pair< T1, T2 > >", "structdetail_1_1is__default__constructible_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ]
      ] ],
      [ "detail::conjunction< is_default_constructible< Ts >... >", "structdetail_1_1conjunction.html", [
        [ "detail::is_default_constructible< const std::tuple< Ts... > >", "structdetail_1_1is__default__constructible_3_01const_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", [
          [ "detail::is_constructible< const std::tuple< Ts... > >", "structdetail_1_1is__constructible_3_01const_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
          [ "detail::is_constructible< const std::tuple< Ts... > >", "structdetail_1_1is__constructible_3_01const_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ]
        ] ],
        [ "detail::is_default_constructible< const std::tuple< Ts... > >", "structdetail_1_1is__default__constructible_3_01const_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
        [ "detail::is_default_constructible< std::tuple< Ts... > >", "structdetail_1_1is__default__constructible_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", [
          [ "detail::is_constructible< std::tuple< Ts... > >", "structdetail_1_1is__constructible_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
          [ "detail::is_constructible< std::tuple< Ts... > >", "structdetail_1_1is__constructible_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ]
        ] ],
        [ "detail::is_default_constructible< std::tuple< Ts... > >", "structdetail_1_1is__default__constructible_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ]
      ] ],
      [ "detail::conjunction< is_constructible< T1, Args >... >", "structdetail_1_1conjunction.html", null ],
      [ "detail::conjunction< is_default_constructible< T1 >, is_default_constructible< T2 > >", "structdetail_1_1conjunction.html", null ],
      [ "detail::conjunction< is_default_constructible< Ts >... >", "structdetail_1_1conjunction.html", null ],
      [ "detail::conjunction<... >", "structdetail_1_1conjunction.html", null ],
      [ "detail::conjunction<... >", "structdetail_1_1conjunction.html", null ],
      [ "detail::is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "structdetail_1_1is__basic__json_3_01NLOHMANN__BASIC__JSON__TPL_01_4.html", null ],
      [ "detail::is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "structdetail_1_1is__basic__json_3_01NLOHMANN__BASIC__JSON__TPL_01_4.html", null ],
      [ "detail::is_comparable< Compare, A, B, void_t< decltype(std::declval< Compare >()(std::declval< A >(), std::declval< B >())), decltype(std::declval< Compare >()(std::declval< B >(), std::declval< A >()))> >", "structdetail_1_1is__comparable_3_01Compare_00_01A_00_01B_00_01void__t_3_01decltype_07std_1_1decle5e3400d312093eca0a7154409c6a227.html", null ],
      [ "detail::is_comparable< Compare, A, B, void_t< decltype(std::declval< Compare >()(std::declval< A >(), std::declval< B >())), decltype(std::declval< Compare >()(std::declval< B >(), std::declval< A >()))> >", "structdetail_1_1is__comparable_3_01Compare_00_01A_00_01B_00_01void__t_3_01decltype_07std_1_1decle5e3400d312093eca0a7154409c6a227.html", null ],
      [ "detail::is_complete_type< T, decltype(void(sizeof(T)))>", "structdetail_1_1is__complete__type_3_01T_00_01decltype_07void_07sizeof_07T_08_08_08_4.html", null ],
      [ "detail::is_complete_type< T, decltype(void(sizeof(T)))>", "structdetail_1_1is__complete__type_3_01T_00_01decltype_07void_07sizeof_07T_08_08_08_4.html", null ],
      [ "detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >", "structdetail_1_1is__constructible__array__type__impl_3_01BasicJsonType_00_01ConstructibleArrayTyff4af2af9684a1cc8580410ec8c319a4.html", null ],
      [ "detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >", "structdetail_1_1is__constructible__array__type__impl_3_01BasicJsonType_00_01ConstructibleArrayTyff4af2af9684a1cc8580410ec8c319a4.html", null ],
      [ "detail::is_json_iterator_of< BasicJsonType, typename BasicJsonType::const_iterator >", "structdetail_1_1is__json__iterator__of_3_01BasicJsonType_00_01typename_01BasicJsonType_1_1const__iterator_01_4.html", null ],
      [ "detail::is_json_iterator_of< BasicJsonType, typename BasicJsonType::const_iterator >", "structdetail_1_1is__json__iterator__of_3_01BasicJsonType_00_01typename_01BasicJsonType_1_1const__iterator_01_4.html", null ],
      [ "detail::is_json_iterator_of< BasicJsonType, typename BasicJsonType::iterator >", "structdetail_1_1is__json__iterator__of_3_01BasicJsonType_00_01typename_01BasicJsonType_1_1iterator_01_4.html", null ],
      [ "detail::is_json_iterator_of< BasicJsonType, typename BasicJsonType::iterator >", "structdetail_1_1is__json__iterator__of_3_01BasicJsonType_00_01typename_01BasicJsonType_1_1iterator_01_4.html", null ],
      [ "detail::is_json_ref< json_ref< T > >", "structdetail_1_1is__json__ref_3_01json__ref_3_01T_01_4_01_4.html", null ],
      [ "detail::is_json_ref< json_ref< T > >", "structdetail_1_1is__json__ref_3_01json__ref_3_01T_01_4_01_4.html", null ],
      [ "detail::is_specialization_of< Primary, Primary< Args... > >", "structdetail_1_1is__specialization__of_3_01Primary_00_01Primary_3_01Args_8_8_8_01_4_01_4.html", null ],
      [ "detail::is_specialization_of< Primary, Primary< Args... > >", "structdetail_1_1is__specialization__of_3_01Primary_00_01Primary_3_01Args_8_8_8_01_4_01_4.html", null ]
    ] ],
    [ "std::tuple_element< N, ::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__element_3_01N_00_01_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01IteratorType_01_4_01_4.html", null ],
    [ "detail::is_ordered_map< T >::two", "structdetail_1_1is__ordered__map_1_1two.html", null ],
    [ "std::conditional::type", null, [
      [ "detail::conjunction< B, Bn... >", "structdetail_1_1conjunction_3_01B_00_01Bn_8_8_8_01_4.html", null ],
      [ "detail::conjunction< B, Bn... >", "structdetail_1_1conjunction_3_01B_00_01Bn_8_8_8_01_4.html", null ]
    ] ],
    [ "UdpClient", "classUdpClient.html", null ],
    [ "UdpServer", "classUdpServer.html", null ],
    [ "detail::value_in_range_of_impl1< OfType, T, NeverOutOfRange, typename >", "structdetail_1_1value__in__range__of__impl1.html", null ],
    [ "detail::value_in_range_of_impl1< OfType, T, false >", "structdetail_1_1value__in__range__of__impl1_3_01OfType_00_01T_00_01false_01_4.html", null ],
    [ "detail::value_in_range_of_impl1< OfType, T, true >", "structdetail_1_1value__in__range__of__impl1_3_01OfType_00_01T_00_01true_01_4.html", null ],
    [ "detail::value_in_range_of_impl2< OfType, T, OfTypeSigned, TSigned >", "structdetail_1_1value__in__range__of__impl2.html", null ],
    [ "detail::value_in_range_of_impl2< OfType, T, false, false >", "structdetail_1_1value__in__range__of__impl2_3_01OfType_00_01T_00_01false_00_01false_01_4.html", null ],
    [ "detail::value_in_range_of_impl2< OfType, T, false, true >", "structdetail_1_1value__in__range__of__impl2_3_01OfType_00_01T_00_01false_00_01true_01_4.html", null ],
    [ "detail::value_in_range_of_impl2< OfType, T, true, false >", "structdetail_1_1value__in__range__of__impl2_3_01OfType_00_01T_00_01true_00_01false_01_4.html", null ],
    [ "detail::value_in_range_of_impl2< OfType, T, true, true >", "structdetail_1_1value__in__range__of__impl2_3_01OfType_00_01T_00_01true_00_01true_01_4.html", null ],
    [ "Vector2", "structVector2.html", null ],
    [ "Vector3", "structVector3.html", null ],
    [ "Vector4", "structVector4.html", null ],
    [ "std::vector< std::pair< const Key, T >, std::allocator< std::pair< const Key, T > > >", null, [
      [ "ordered_map< Key, T, IgnoredLess, Allocator >", "structordered__map.html", null ],
      [ "ordered_map< Key, T, IgnoredLess, Allocator >", "structordered__map.html", null ]
    ] ],
    [ "ecs::Velocity", "structecs_1_1Velocity.html", null ],
    [ "VkAcquireNextImageInfoKHR", "structVkAcquireNextImageInfoKHR.html", null ],
    [ "VkAllocationCallbacks", "structVkAllocationCallbacks.html", null ],
    [ "VkApplicationInfo", "structVkApplicationInfo.html", null ],
    [ "VkAttachmentDescription", "structVkAttachmentDescription.html", null ],
    [ "VkAttachmentReference", "structVkAttachmentReference.html", null ],
    [ "VkBaseInStructure", "structVkBaseInStructure.html", null ],
    [ "VkBaseOutStructure", "structVkBaseOutStructure.html", null ],
    [ "VkBindBufferMemoryDeviceGroupInfo", "structVkBindBufferMemoryDeviceGroupInfo.html", null ],
    [ "VkBindBufferMemoryInfo", "structVkBindBufferMemoryInfo.html", null ],
    [ "VkBindImageMemoryDeviceGroupInfo", "structVkBindImageMemoryDeviceGroupInfo.html", null ],
    [ "VkBindImageMemoryInfo", "structVkBindImageMemoryInfo.html", null ],
    [ "VkBindImageMemorySwapchainInfoKHR", "structVkBindImageMemorySwapchainInfoKHR.html", null ],
    [ "VkBindImagePlaneMemoryInfo", "structVkBindImagePlaneMemoryInfo.html", null ],
    [ "VkBindSparseInfo", "structVkBindSparseInfo.html", null ],
    [ "VkBufferCopy", "structVkBufferCopy.html", null ],
    [ "VkBufferCreateInfo", "structVkBufferCreateInfo.html", null ],
    [ "VkBufferImageCopy", "structVkBufferImageCopy.html", null ],
    [ "VkBufferMemoryBarrier", "structVkBufferMemoryBarrier.html", null ],
    [ "VkBufferMemoryRequirementsInfo2", "structVkBufferMemoryRequirementsInfo2.html", null ],
    [ "VkBufferViewCreateInfo", "structVkBufferViewCreateInfo.html", null ],
    [ "VkClearAttachment", "structVkClearAttachment.html", null ],
    [ "VkClearColorValue", "unionVkClearColorValue.html", null ],
    [ "VkClearDepthStencilValue", "structVkClearDepthStencilValue.html", null ],
    [ "VkClearRect", "structVkClearRect.html", null ],
    [ "VkClearValue", "unionVkClearValue.html", null ],
    [ "VkCommandBufferAllocateInfo", "structVkCommandBufferAllocateInfo.html", null ],
    [ "VkCommandBufferBeginInfo", "structVkCommandBufferBeginInfo.html", null ],
    [ "VkCommandBufferInheritanceInfo", "structVkCommandBufferInheritanceInfo.html", null ],
    [ "VkCommandPoolCreateInfo", "structVkCommandPoolCreateInfo.html", null ],
    [ "VkComponentMapping", "structVkComponentMapping.html", null ],
    [ "VkComputePipelineCreateInfo", "structVkComputePipelineCreateInfo.html", null ],
    [ "VkCopyDescriptorSet", "structVkCopyDescriptorSet.html", null ],
    [ "VkDebugReportCallbackCreateInfoEXT", "structVkDebugReportCallbackCreateInfoEXT.html", null ],
    [ "VkDescriptorBufferInfo", "structVkDescriptorBufferInfo.html", null ],
    [ "VkDescriptorImageInfo", "structVkDescriptorImageInfo.html", null ],
    [ "VkDescriptorPoolCreateInfo", "structVkDescriptorPoolCreateInfo.html", null ],
    [ "VkDescriptorPoolSize", "structVkDescriptorPoolSize.html", null ],
    [ "VkDescriptorSetAllocateInfo", "structVkDescriptorSetAllocateInfo.html", null ],
    [ "VkDescriptorSetLayoutBinding", "structVkDescriptorSetLayoutBinding.html", null ],
    [ "VkDescriptorSetLayoutCreateInfo", "structVkDescriptorSetLayoutCreateInfo.html", null ],
    [ "VkDescriptorSetLayoutSupport", "structVkDescriptorSetLayoutSupport.html", null ],
    [ "VkDescriptorUpdateTemplateCreateInfo", "structVkDescriptorUpdateTemplateCreateInfo.html", null ],
    [ "VkDescriptorUpdateTemplateEntry", "structVkDescriptorUpdateTemplateEntry.html", null ],
    [ "VkDeviceCreateInfo", "structVkDeviceCreateInfo.html", null ],
    [ "VkDeviceGroupBindSparseInfo", "structVkDeviceGroupBindSparseInfo.html", null ],
    [ "VkDeviceGroupCommandBufferBeginInfo", "structVkDeviceGroupCommandBufferBeginInfo.html", null ],
    [ "VkDeviceGroupDeviceCreateInfo", "structVkDeviceGroupDeviceCreateInfo.html", null ],
    [ "VkDeviceGroupPresentCapabilitiesKHR", "structVkDeviceGroupPresentCapabilitiesKHR.html", null ],
    [ "VkDeviceGroupPresentInfoKHR", "structVkDeviceGroupPresentInfoKHR.html", null ],
    [ "VkDeviceGroupRenderPassBeginInfo", "structVkDeviceGroupRenderPassBeginInfo.html", null ],
    [ "VkDeviceGroupSubmitInfo", "structVkDeviceGroupSubmitInfo.html", null ],
    [ "VkDeviceGroupSwapchainCreateInfoKHR", "structVkDeviceGroupSwapchainCreateInfoKHR.html", null ],
    [ "VkDeviceQueueCreateInfo", "structVkDeviceQueueCreateInfo.html", null ],
    [ "VkDeviceQueueInfo2", "structVkDeviceQueueInfo2.html", null ],
    [ "VkDispatchIndirectCommand", "structVkDispatchIndirectCommand.html", null ],
    [ "VkDrawIndexedIndirectCommand", "structVkDrawIndexedIndirectCommand.html", null ],
    [ "VkDrawIndirectCommand", "structVkDrawIndirectCommand.html", null ],
    [ "VkEventCreateInfo", "structVkEventCreateInfo.html", null ],
    [ "VkExportFenceCreateInfo", "structVkExportFenceCreateInfo.html", null ],
    [ "VkExportMemoryAllocateInfo", "structVkExportMemoryAllocateInfo.html", null ],
    [ "VkExportSemaphoreCreateInfo", "structVkExportSemaphoreCreateInfo.html", null ],
    [ "VkExtensionProperties", "structVkExtensionProperties.html", null ],
    [ "VkExtent2D", "structVkExtent2D.html", null ],
    [ "VkExtent3D", "structVkExtent3D.html", null ],
    [ "VkExternalBufferProperties", "structVkExternalBufferProperties.html", null ],
    [ "VkExternalFenceProperties", "structVkExternalFenceProperties.html", null ],
    [ "VkExternalImageFormatProperties", "structVkExternalImageFormatProperties.html", null ],
    [ "VkExternalMemoryBufferCreateInfo", "structVkExternalMemoryBufferCreateInfo.html", null ],
    [ "VkExternalMemoryImageCreateInfo", "structVkExternalMemoryImageCreateInfo.html", null ],
    [ "VkExternalMemoryProperties", "structVkExternalMemoryProperties.html", null ],
    [ "VkExternalSemaphoreProperties", "structVkExternalSemaphoreProperties.html", null ],
    [ "VkFenceCreateInfo", "structVkFenceCreateInfo.html", null ],
    [ "VkFormatProperties", "structVkFormatProperties.html", null ],
    [ "VkFormatProperties2", "structVkFormatProperties2.html", null ],
    [ "VkFramebufferCreateInfo", "structVkFramebufferCreateInfo.html", null ],
    [ "VkGraphicsPipelineCreateInfo", "structVkGraphicsPipelineCreateInfo.html", null ],
    [ "VkImageBlit", "structVkImageBlit.html", null ],
    [ "VkImageCopy", "structVkImageCopy.html", null ],
    [ "VkImageCreateInfo", "structVkImageCreateInfo.html", null ],
    [ "VkImageFormatProperties", "structVkImageFormatProperties.html", null ],
    [ "VkImageFormatProperties2", "structVkImageFormatProperties2.html", null ],
    [ "VkImageMemoryBarrier", "structVkImageMemoryBarrier.html", null ],
    [ "VkImageMemoryRequirementsInfo2", "structVkImageMemoryRequirementsInfo2.html", null ],
    [ "VkImagePlaneMemoryRequirementsInfo", "structVkImagePlaneMemoryRequirementsInfo.html", null ],
    [ "VkImageResolve", "structVkImageResolve.html", null ],
    [ "VkImageSparseMemoryRequirementsInfo2", "structVkImageSparseMemoryRequirementsInfo2.html", null ],
    [ "VkImageSubresource", "structVkImageSubresource.html", null ],
    [ "VkImageSubresourceLayers", "structVkImageSubresourceLayers.html", null ],
    [ "VkImageSubresourceRange", "structVkImageSubresourceRange.html", null ],
    [ "VkImageSwapchainCreateInfoKHR", "structVkImageSwapchainCreateInfoKHR.html", null ],
    [ "VkImageViewCreateInfo", "structVkImageViewCreateInfo.html", null ],
    [ "VkImageViewUsageCreateInfo", "structVkImageViewUsageCreateInfo.html", null ],
    [ "VkInputAttachmentAspectReference", "structVkInputAttachmentAspectReference.html", null ],
    [ "VkInstanceCreateInfo", "structVkInstanceCreateInfo.html", null ],
    [ "VkLayerProperties", "structVkLayerProperties.html", null ],
    [ "VkMacOSSurfaceCreateInfoMVK", "structVkMacOSSurfaceCreateInfoMVK.html", null ],
    [ "VkMappedMemoryRange", "structVkMappedMemoryRange.html", null ],
    [ "VkMemoryAllocateFlagsInfo", "structVkMemoryAllocateFlagsInfo.html", null ],
    [ "VkMemoryAllocateInfo", "structVkMemoryAllocateInfo.html", null ],
    [ "VkMemoryBarrier", "structVkMemoryBarrier.html", null ],
    [ "VkMemoryDedicatedAllocateInfo", "structVkMemoryDedicatedAllocateInfo.html", null ],
    [ "VkMemoryDedicatedRequirements", "structVkMemoryDedicatedRequirements.html", null ],
    [ "VkMemoryHeap", "structVkMemoryHeap.html", null ],
    [ "VkMemoryRequirements", "structVkMemoryRequirements.html", null ],
    [ "VkMemoryRequirements2", "structVkMemoryRequirements2.html", null ],
    [ "VkMemoryType", "structVkMemoryType.html", null ],
    [ "VkMetalSurfaceCreateInfoEXT", "structVkMetalSurfaceCreateInfoEXT.html", null ],
    [ "VkOffset2D", "structVkOffset2D.html", null ],
    [ "VkOffset3D", "structVkOffset3D.html", null ],
    [ "VkPhysicalDevice16BitStorageFeatures", "structVkPhysicalDevice16BitStorageFeatures.html", null ],
    [ "VkPhysicalDeviceExternalBufferInfo", "structVkPhysicalDeviceExternalBufferInfo.html", null ],
    [ "VkPhysicalDeviceExternalFenceInfo", "structVkPhysicalDeviceExternalFenceInfo.html", null ],
    [ "VkPhysicalDeviceExternalImageFormatInfo", "structVkPhysicalDeviceExternalImageFormatInfo.html", null ],
    [ "VkPhysicalDeviceExternalSemaphoreInfo", "structVkPhysicalDeviceExternalSemaphoreInfo.html", null ],
    [ "VkPhysicalDeviceFeatures", "structVkPhysicalDeviceFeatures.html", null ],
    [ "VkPhysicalDeviceFeatures2", "structVkPhysicalDeviceFeatures2.html", null ],
    [ "VkPhysicalDeviceGroupProperties", "structVkPhysicalDeviceGroupProperties.html", null ],
    [ "VkPhysicalDeviceIDProperties", "structVkPhysicalDeviceIDProperties.html", null ],
    [ "VkPhysicalDeviceImageFormatInfo2", "structVkPhysicalDeviceImageFormatInfo2.html", null ],
    [ "VkPhysicalDeviceLimits", "structVkPhysicalDeviceLimits.html", null ],
    [ "VkPhysicalDeviceMaintenance3Properties", "structVkPhysicalDeviceMaintenance3Properties.html", null ],
    [ "VkPhysicalDeviceMemoryProperties", "structVkPhysicalDeviceMemoryProperties.html", null ],
    [ "VkPhysicalDeviceMemoryProperties2", "structVkPhysicalDeviceMemoryProperties2.html", null ],
    [ "VkPhysicalDeviceMultiviewFeatures", "structVkPhysicalDeviceMultiviewFeatures.html", null ],
    [ "VkPhysicalDeviceMultiviewProperties", "structVkPhysicalDeviceMultiviewProperties.html", null ],
    [ "VkPhysicalDevicePointClippingProperties", "structVkPhysicalDevicePointClippingProperties.html", null ],
    [ "VkPhysicalDeviceProperties", "structVkPhysicalDeviceProperties.html", null ],
    [ "VkPhysicalDeviceProperties2", "structVkPhysicalDeviceProperties2.html", null ],
    [ "VkPhysicalDeviceProtectedMemoryFeatures", "structVkPhysicalDeviceProtectedMemoryFeatures.html", null ],
    [ "VkPhysicalDeviceProtectedMemoryProperties", "structVkPhysicalDeviceProtectedMemoryProperties.html", null ],
    [ "VkPhysicalDeviceSamplerYcbcrConversionFeatures", "structVkPhysicalDeviceSamplerYcbcrConversionFeatures.html", null ],
    [ "VkPhysicalDeviceShaderDrawParametersFeatures", "structVkPhysicalDeviceShaderDrawParametersFeatures.html", null ],
    [ "VkPhysicalDeviceSparseImageFormatInfo2", "structVkPhysicalDeviceSparseImageFormatInfo2.html", null ],
    [ "VkPhysicalDeviceSparseProperties", "structVkPhysicalDeviceSparseProperties.html", null ],
    [ "VkPhysicalDeviceSubgroupProperties", "structVkPhysicalDeviceSubgroupProperties.html", null ],
    [ "VkPhysicalDeviceVariablePointersFeatures", "structVkPhysicalDeviceVariablePointersFeatures.html", null ],
    [ "VkPipelineCacheCreateInfo", "structVkPipelineCacheCreateInfo.html", null ],
    [ "VkPipelineColorBlendAttachmentState", "structVkPipelineColorBlendAttachmentState.html", null ],
    [ "VkPipelineColorBlendStateCreateInfo", "structVkPipelineColorBlendStateCreateInfo.html", null ],
    [ "VkPipelineDepthStencilStateCreateInfo", "structVkPipelineDepthStencilStateCreateInfo.html", null ],
    [ "VkPipelineDynamicStateCreateInfo", "structVkPipelineDynamicStateCreateInfo.html", null ],
    [ "VkPipelineInputAssemblyStateCreateInfo", "structVkPipelineInputAssemblyStateCreateInfo.html", null ],
    [ "VkPipelineLayoutCreateInfo", "structVkPipelineLayoutCreateInfo.html", null ],
    [ "VkPipelineMultisampleStateCreateInfo", "structVkPipelineMultisampleStateCreateInfo.html", null ],
    [ "VkPipelineRasterizationStateCreateInfo", "structVkPipelineRasterizationStateCreateInfo.html", null ],
    [ "VkPipelineShaderStageCreateInfo", "structVkPipelineShaderStageCreateInfo.html", null ],
    [ "VkPipelineTessellationDomainOriginStateCreateInfo", "structVkPipelineTessellationDomainOriginStateCreateInfo.html", null ],
    [ "VkPipelineTessellationStateCreateInfo", "structVkPipelineTessellationStateCreateInfo.html", null ],
    [ "VkPipelineVertexInputStateCreateInfo", "structVkPipelineVertexInputStateCreateInfo.html", null ],
    [ "VkPipelineViewportStateCreateInfo", "structVkPipelineViewportStateCreateInfo.html", null ],
    [ "VkPresentInfoKHR", "structVkPresentInfoKHR.html", null ],
    [ "VkProtectedSubmitInfo", "structVkProtectedSubmitInfo.html", null ],
    [ "VkPushConstantRange", "structVkPushConstantRange.html", null ],
    [ "VkQueryPoolCreateInfo", "structVkQueryPoolCreateInfo.html", null ],
    [ "VkQueueFamilyProperties", "structVkQueueFamilyProperties.html", null ],
    [ "VkQueueFamilyProperties2", "structVkQueueFamilyProperties2.html", null ],
    [ "VkRect2D", "structVkRect2D.html", null ],
    [ "VkRenderPassBeginInfo", "structVkRenderPassBeginInfo.html", null ],
    [ "VkRenderPassCreateInfo", "structVkRenderPassCreateInfo.html", null ],
    [ "VkRenderPassInputAttachmentAspectCreateInfo", "structVkRenderPassInputAttachmentAspectCreateInfo.html", null ],
    [ "VkRenderPassMultiviewCreateInfo", "structVkRenderPassMultiviewCreateInfo.html", null ],
    [ "VkSamplerCreateInfo", "structVkSamplerCreateInfo.html", null ],
    [ "VkSamplerYcbcrConversionCreateInfo", "structVkSamplerYcbcrConversionCreateInfo.html", null ],
    [ "VkSamplerYcbcrConversionImageFormatProperties", "structVkSamplerYcbcrConversionImageFormatProperties.html", null ],
    [ "VkSamplerYcbcrConversionInfo", "structVkSamplerYcbcrConversionInfo.html", null ],
    [ "VkSemaphoreCreateInfo", "structVkSemaphoreCreateInfo.html", null ],
    [ "VkShaderModuleCreateInfo", "structVkShaderModuleCreateInfo.html", null ],
    [ "VkSparseBufferMemoryBindInfo", "structVkSparseBufferMemoryBindInfo.html", null ],
    [ "VkSparseImageFormatProperties", "structVkSparseImageFormatProperties.html", null ],
    [ "VkSparseImageFormatProperties2", "structVkSparseImageFormatProperties2.html", null ],
    [ "VkSparseImageMemoryBind", "structVkSparseImageMemoryBind.html", null ],
    [ "VkSparseImageMemoryBindInfo", "structVkSparseImageMemoryBindInfo.html", null ],
    [ "VkSparseImageMemoryRequirements", "structVkSparseImageMemoryRequirements.html", null ],
    [ "VkSparseImageMemoryRequirements2", "structVkSparseImageMemoryRequirements2.html", null ],
    [ "VkSparseImageOpaqueMemoryBindInfo", "structVkSparseImageOpaqueMemoryBindInfo.html", null ],
    [ "VkSparseMemoryBind", "structVkSparseMemoryBind.html", null ],
    [ "VkSpecializationInfo", "structVkSpecializationInfo.html", null ],
    [ "VkSpecializationMapEntry", "structVkSpecializationMapEntry.html", null ],
    [ "VkStencilOpState", "structVkStencilOpState.html", null ],
    [ "VkSubmitInfo", "structVkSubmitInfo.html", null ],
    [ "VkSubpassDependency", "structVkSubpassDependency.html", null ],
    [ "VkSubpassDescription", "structVkSubpassDescription.html", null ],
    [ "VkSubresourceLayout", "structVkSubresourceLayout.html", null ],
    [ "VkSurfaceCapabilitiesKHR", "structVkSurfaceCapabilitiesKHR.html", null ],
    [ "VkSurfaceFormatKHR", "structVkSurfaceFormatKHR.html", null ],
    [ "VkSwapchainCreateInfoKHR", "structVkSwapchainCreateInfoKHR.html", null ],
    [ "VkVertexInputAttributeDescription", "structVkVertexInputAttributeDescription.html", null ],
    [ "VkVertexInputBindingDescription", "structVkVertexInputBindingDescription.html", null ],
    [ "VkViewport", "structVkViewport.html", null ],
    [ "VkWaylandSurfaceCreateInfoKHR", "structVkWaylandSurfaceCreateInfoKHR.html", null ],
    [ "VkWin32SurfaceCreateInfoKHR", "structVkWin32SurfaceCreateInfoKHR.html", null ],
    [ "VkWriteDescriptorSet", "structVkWriteDescriptorSet.html", null ],
    [ "VkXcbSurfaceCreateInfoKHR", "structVkXcbSurfaceCreateInfoKHR.html", null ],
    [ "VkXlibSurfaceCreateInfoKHR", "structVkXlibSurfaceCreateInfoKHR.html", null ],
    [ "VoxArray3D", "structVoxArray3D.html", null ],
    [ "VoxColor", "structVoxColor.html", null ],
    [ "VoxVector3", "structVoxVector3.html", null ],
    [ "VrDeviceInfo", "structVrDeviceInfo.html", null ],
    [ "VrStereoConfig", "structVrStereoConfig.html", null ],
    [ "Wave", "structWave.html", null ],
    [ "WaveTextConfig", "structWaveTextConfig.html", null ],
    [ "detail::wide_string_input_adapter< BaseInputAdapter, WideCharType >", "classdetail_1_1wide__string__input__adapter.html", null ],
    [ "detail::wide_string_input_helper< BaseInputAdapter, T >", "structdetail_1_1wide__string__input__helper.html", null ],
    [ "detail::wide_string_input_helper< BaseInputAdapter, 2 >", "structdetail_1_1wide__string__input__helper_3_01BaseInputAdapter_00_012_01_4.html", null ],
    [ "detail::wide_string_input_helper< BaseInputAdapter, 4 >", "structdetail_1_1wide__string__input__helper_3_01BaseInputAdapter_00_014_01_4.html", null ],
    [ "wl_cursor", "structwl__cursor.html", null ],
    [ "wl_cursor_image", "structwl__cursor__image.html", null ]
];